import { emitNamedTsType, schemaToTsType, type OpenApiSchema } from "@crossengin/operate-runtime";

import type { WebApiDescriptor, WebRouteDescriptor } from "./describe.js";

/**
 * A pure, deterministic `WebApiDescriptor` → TypeScript client emitter (P3.39) —
 * the operate-web parity of operate-server's OpenAPI client emitter (P3.38). It
 * turns the descriptor served at `GET /ui/_describe` into one self-contained `.ts`
 * module: an interface per view-model (`models`) + per-entity field shape
 * (`entities[].schema`), and a `createWebClient` factory with a typed method per
 * route (return types from each route's `responseSchema`, `#/models/<Name>` `$ref`s
 * resolving to the emitted model interfaces). Works purely off the descriptor.
 */
export interface EmitWebClientOptions {
  /** The exported client factory name (default `createWebClient`). */
  readonly clientName?: string;
}

const DEFAULT_CLIENT_NAME = "createWebClient";

function pascal(name: string): string {
  return name.length === 0 ? name : name[0]!.toUpperCase() + name.slice(1);
}

function camel(name: string): string {
  return name.length === 0 ? name : name[0]!.toLowerCase() + name.slice(1);
}

/** A method name for a route: `<entity><Kind>`, transitions as `<entity><Transition>`. */
export function webMethodName(route: WebRouteDescriptor): string {
  if (route.entity === undefined) return route.kind; // global routes: app / describe
  const entity = camel(route.entity);
  if (route.kind === "transition" && route.transition !== undefined) {
    return `${entity}${pascal(route.transition)}`;
  }
  return `${entity}${pascal(route.kind)}`;
}

/** The `{param}` placeholders in a path template, in order. */
function pathParamNames(path: string): readonly string[] {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]!);
}

/** Emits one client method for a route. */
function emitMethod(route: WebRouteDescriptor): string | undefined {
  if (route.kind === "describe") return undefined; // the descriptor itself; not a data route
  const params = pathParamNames(route.path);
  const ret = route.responseSchema !== undefined ? schemaToTsType(route.responseSchema) : "void";

  const sig: string[] = params.map((p) => `${p}: string`);
  // create/update carry the entity body; transition bakes its name into the body.
  const hasBody = route.entity !== undefined && (route.kind === "create" || route.kind === "update");
  if (hasBody) sig.push(`body: ${route.entity!}`);
  sig.push("query?: QueryParams");

  const tmpl = route.path.replace(/\{([^}]+)\}/g, (_m, p: string) => `\${encodeURIComponent(${p})}`);
  let bodyArg = "";
  if (hasBody) bodyArg = ", body";
  else if (route.kind === "transition" && route.transition !== undefined) {
    bodyArg = `, { transition: ${JSON.stringify(route.transition)} }`;
  }
  const call = `request("${route.method}", \`${tmpl}\${buildQuery(query)}\`${bodyArg})`;

  const retType = ret === "void" ? "void" : ret;
  return `  ${webMethodName(route)}: (${sig.join(", ")}): Promise<${retType}> =>\n    ${call} as Promise<${retType}>,`;
}

const PREAMBLE = `// GENERATED by operate-server \`web-client\` — do not edit by hand.
// A typed view-model client projected from the GET /ui/_describe descriptor.

export type QueryParams = Record<string, string | number | boolean | undefined>;

export interface ClientOptions {
  readonly baseUrl: string;
  readonly token?: string;
  readonly fetch?: typeof globalThis.fetch;
}

export class WebApiError extends Error {
  readonly status: number;
  readonly problem: unknown;
  constructor(status: number, problem: unknown) {
    super(\`HTTP \${status}\`);
    this.name = "WebApiError";
    this.status = status;
    this.problem = problem;
  }
}

function buildQuery(query?: QueryParams): string {
  if (query === undefined) return "";
  const parts: string[] = [];
  for (const [k, v] of Object.entries(query)) {
    if (v !== undefined) parts.push(\`\${encodeURIComponent(k)}=\${encodeURIComponent(String(v))}\`);
  }
  return parts.length > 0 ? \`?\${parts.join("&")}\` : "";
}`;

/**
 * Emits the complete self-contained TypeScript view-model client module for a
 * `WebApiDescriptor`: the preamble, an interface per view-model + per-entity field
 * shape, and the `createWebClient` factory with a method per route. Deterministic.
 */
export function emitWebClientModule(descriptor: WebApiDescriptor, options: EmitWebClientOptions = {}): string {
  const clientName = options.clientName ?? DEFAULT_CLIENT_NAME;

  // View-model interfaces (TableModel/DetailModel/…) then per-entity field shapes.
  const modelTypes = Object.entries(descriptor.models)
    .map(([name, schema]) => emitNamedTsType(name, schema as OpenApiSchema))
    .join("\n\n");
  const entityTypes = descriptor.entities
    .map((e) => emitNamedTsType(e.entity, e.schema as OpenApiSchema))
    .join("\n\n");

  const methods: string[] = [];
  for (const route of descriptor.routes) {
    const m = emitMethod(route);
    if (m !== undefined) methods.push(m);
  }
  for (const entity of descriptor.entities) {
    for (const route of entity.routes) {
      const m = emitMethod(route);
      if (m !== undefined) methods.push(m);
    }
  }

  const factory = `export function ${clientName}(options: ClientOptions) {
  const doFetch = options.fetch ?? globalThis.fetch;
  async function request(method: string, path: string, body?: unknown): Promise<unknown> {
    const headers: Record<string, string> = { accept: "application/json" };
    if (body !== undefined) headers["content-type"] = "application/json";
    if (options.token !== undefined) headers["authorization"] = \`Bearer \${options.token}\`;
    const res = await doFetch(\`\${options.baseUrl}\${path}\`, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (res.status === 204) return undefined;
    const payload: unknown = await res.json().catch(() => undefined);
    if (!res.ok) throw new WebApiError(res.status, payload);
    return payload;
  }
  return {
${methods.join("\n")}
  };
}`;

  return `${PREAMBLE}\n\n${modelTypes}\n\n${entityTypes}\n\n${factory}\n`;
}
