import type { OpenApiDocument, OpenApiOperationObject, OpenApiResponse } from "./openapi.js";
import type { OpenApiSchema } from "./schemas.js";

/**
 * A pure, deterministic OpenAPI 3.1 → **Ruby** client emitter (P3.47) — the
 * fifth-language sibling of the TS / Python / Go / PHP emitters, driven off the
 * same `OpenApiDocument`. It produces one self-contained `.rb` file (Ruby 3.x,
 * stdlib only — `net/http` + `json` + `uri`): a class per object schema (attr
 * readers + a `from_h` factory) + an `OperateClient` with a snake_case method per
 * operation. No third-party gem (no Faraday/HTTParty).
 */
export interface EmitRubyClientOptions {
  /** The emitted client class name (default `OperateClient`). */
  readonly className?: string;
}

const DEFAULT_CLASS_NAME = "OperateClient";

/** `#/components/schemas/Product` → `Product`. */
function refName(ref: string): string {
  const i = ref.lastIndexOf("/");
  return i >= 0 ? ref.slice(i + 1) : ref;
}

/** `salesOrder` → `sales_order`. */
function camelToSnake(part: string): string {
  return part.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
}

/** `salesOrder.create` / `product.list` → `sales_order_create` / `product_list`. */
export function rubyMethodName(operationId: string): string {
  return operationId
    .split(/[._\-/]+/)
    .filter((p) => p.length > 0)
    .map(camelToSnake)
    .join("_");
}

/** The `{param}` placeholders in a path template, in order. */
function pathParamNames(path: string): readonly string[] {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]!);
}

/** Emits a class for one named object schema (oneOf/alias schemas stay plain Hashes → no class). */
function emitNamedRubyClass(name: string, schema: OpenApiSchema): string | null {
  if (schema.properties === undefined) return null;
  const fields = Object.keys(schema.properties);
  if (fields.length === 0) {
    return [`class ${name}`, `  def self.from_h(_h = {})`, `    new`, `  end`, `end`].join("\n");
  }
  const readers = `  attr_reader ${fields.map((f) => `:${f}`).join(", ")}`;
  const assigns = fields.map((f) => `    @${f} = h[${JSON.stringify(f)}]`);
  return [
    `class ${name}`,
    readers,
    ``,
    `  def initialize(h = {})`,
    ...assigns,
    `  end`,
    ``,
    `  def self.from_h(h)`,
    `    new(h || {})`,
    `  end`,
    `end`,
  ].join("\n");
}

/** The success response of an operation (200 → 201 → 204), or undefined. */
function successResponse(op: OpenApiOperationObject): { readonly status: string; readonly response: OpenApiResponse } | undefined {
  for (const status of ["200", "201", "204"]) {
    const response = op.responses[status];
    if (response !== undefined) return { status, response };
  }
  return undefined;
}

/** The class to hydrate the response into (a `$ref`), or null (raw Hash/Array/nil). */
function hydrateClassFor(op: OpenApiOperationObject): string | null {
  const success = successResponse(op);
  if (success === undefined || success.status === "204") return null;
  const schema = success.response.content?.["application/json"]?.schema;
  if (schema?.$ref !== undefined) return refName(schema.$ref);
  return null;
}

/** Emits one client method. */
function emitMethod(method: string, path: string, op: OpenApiOperationObject): string {
  const params = pathParamNames(path);
  const hasBody = op.requestBody?.content["application/json"]?.schema !== undefined;
  const hydrate = hydrateClassFor(op);

  const args: string[] = [...params];
  if (hasBody) args.push("body");
  args.push("query: {}");
  const argList = args.length > 0 ? `(${args.join(", ")})` : "";

  const tmpl = path.replace(/\{([^}]+)\}/g, (_m, p: string) => `#{URI.encode_www_form_component(${p})}`);
  const pathExpr = `"${tmpl}" + build_query(query)`;
  const bodyArg = hasBody ? ", body" : "";
  const call = `request(${JSON.stringify(method.toUpperCase())}, ${pathExpr}${bodyArg})`;

  const inner = hydrate !== null ? `    ${hydrate}.from_h(${call})` : `    ${call}`;
  return [`  def ${rubyMethodName(op.operationId)}${argList}`, inner, `  end`].join("\n");
}

const PREAMBLE = `# frozen_string_literal: true

# GENERATED by operate-server \`openapi-client --lang ruby\` — do not edit by hand.
# A typed stdlib client (Ruby 3.x, net/http + json) projected from the served OpenAPI 3.1 document.

require "json"
require "net/http"
require "uri"

class OperateApiError < StandardError
  attr_reader :status, :problem

  def initialize(status, problem)
    @status = status
    @problem = problem
    super("operate: HTTP #{status}")
  end
end`;

/**
 * Emits the complete self-contained Ruby client file for a served OpenAPI document:
 * the preamble (error type + requires), a class per object schema, and the client
 * class with a method per operation. Deterministic — the same document always
 * yields the same source.
 */
export function emitOperateRubyClient(doc: OpenApiDocument, options: EmitRubyClientOptions = {}): string {
  const className = options.className ?? DEFAULT_CLASS_NAME;
  const schemas = doc.components?.schemas ?? {};

  const classes = Object.entries(schemas)
    .map(([name, schema]) => emitNamedRubyClass(name, schema))
    .filter((c): c is string => c !== null)
    .join("\n\n");

  const methods: string[] = [];
  const httpMethods = ["get", "post", "put", "patch", "delete"];
  for (const [path, item] of Object.entries(doc.paths)) {
    for (const method of httpMethods) {
      const op = (item as Record<string, OpenApiOperationObject | undefined>)[method];
      if (op !== undefined) methods.push(emitMethod(method, path, op));
    }
  }

  const clientClass = `class ${className}
  def initialize(base_url, token: nil)
    @base_url = base_url.to_s.chomp("/")
    @token = token
  end

${methods.join("\n\n")}

  private

  def build_query(query)
    return "" if query.nil? || query.empty?

    "?" + URI.encode_www_form(query)
  end

  def request(method, path, body = nil)
    uri = URI(@base_url + path)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme == "https"
    klass = {
      "GET" => Net::HTTP::Get,
      "POST" => Net::HTTP::Post,
      "PUT" => Net::HTTP::Put,
      "PATCH" => Net::HTTP::Patch,
      "DELETE" => Net::HTTP::Delete
    }.fetch(method)
    req = klass.new(uri)
    req["Accept"] = "application/json"
    unless body.nil?
      req["Content-Type"] = "application/json"
      req.body = JSON.generate(body)
    end
    req["Authorization"] = "Bearer #{@token}" unless @token.nil?
    res = http.request(req)
    code = res.code.to_i
    raw = res.body
    if code >= 400
      problem = begin
        raw.nil? ? nil : JSON.parse(raw)
      rescue JSON::ParserError
        nil
      end
      raise OperateApiError.new(code, problem)
    end
    return nil if code == 204 || raw.nil? || raw.empty?

    JSON.parse(raw)
  end
end`;

  return `${PREAMBLE}\n\n${classes}\n\n${clientClass}\n`;
}
