export const SUBCOMMANDS = [
  "init",
  "validate",
  "diff",
  "patch",
  "hash",
  "apply",
  "chat",
  "sessions",
  "gateway",
  "retention",
  "tenant",
  "tenants",
  "workflow",
  "version",
  "help",
] as const;
export type Subcommand = (typeof SUBCOMMANDS)[number];

export const OUTPUT_FORMATS = ["human", "json", "csv", "tsv", "ndjson", "yaml"] as const;
export type OutputFormat = (typeof OUTPUT_FORMATS)[number];

export interface ParsedCommand {
  readonly subcommand: Subcommand;
  readonly positional: readonly string[];
  readonly flags: ReadonlyMap<string, string | true>;
  readonly multiFlags: ReadonlyMap<string, ReadonlyArray<string>>;
  readonly format: OutputFormat;
}

export interface ParseError {
  readonly kind: "parse_error";
  readonly message: string;
}

export type ParseResult =
  | { readonly ok: true; readonly command: ParsedCommand }
  | { readonly ok: false; readonly error: ParseError };

export function parseArgs(argv: readonly string[]): ParseResult {
  const args = argv.slice(2);
  const positional: string[] = [];
  const flags = new Map<string, string | true>();
  const multiFlags = new Map<string, string[]>();

  function recordFlag(name: string, value: string | true): void {
    flags.set(name, value);
    if (typeof value === "string") {
      const existing = multiFlags.get(name);
      if (existing !== undefined) {
        existing.push(value);
      } else {
        multiFlags.set(name, [value]);
      }
    }
  }

  let subcommandRaw: string | null = null;

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]!;
    if (arg.startsWith("--")) {
      const eq = arg.indexOf("=");
      if (eq >= 0) {
        recordFlag(arg.slice(2, eq), arg.slice(eq + 1));
      } else {
        const next = args[i + 1];
        if (next !== undefined && !next.startsWith("--")) {
          recordFlag(arg.slice(2), next);
          i += 1;
        } else {
          recordFlag(arg.slice(2), true);
        }
      }
      continue;
    }
    if (subcommandRaw === null) {
      subcommandRaw = arg;
    } else {
      positional.push(arg);
    }
  }

  if (subcommandRaw === null) {
    return {
      ok: true,
      command: {
        subcommand: "help",
        positional,
        flags,
        multiFlags,
        format: "human",
      },
    };
  }
  if (!isSubcommand(subcommandRaw)) {
    return {
      ok: false,
      error: { kind: "parse_error", message: `unknown subcommand: ${subcommandRaw}` },
    };
  }
  const formatRaw = flags.get("format");
  let format: OutputFormat = "human";
  if (typeof formatRaw === "string") {
    if (
      formatRaw !== "human" &&
      formatRaw !== "json" &&
      formatRaw !== "csv" &&
      formatRaw !== "tsv" &&
      formatRaw !== "ndjson" &&
      formatRaw !== "yaml"
    ) {
      return {
        ok: false,
        error: { kind: "parse_error", message: `unknown output format: ${formatRaw}` },
      };
    }
    format = formatRaw;
  }
  return {
    ok: true,
    command: { subcommand: subcommandRaw, positional, flags, multiFlags, format },
  };
}

export function isSubcommand(value: unknown): value is Subcommand {
  return typeof value === "string" && (SUBCOMMANDS as readonly string[]).includes(value);
}

export function getStringFlag(command: ParsedCommand, name: string): string | null {
  const value = command.flags.get(name);
  if (typeof value === "string") return value;
  return null;
}

export function getBooleanFlag(command: ParsedCommand, name: string): boolean {
  const value = command.flags.get(name);
  return value === true || value === "true" || value === "1";
}

export function getMultiFlag(command: ParsedCommand, name: string): ReadonlyArray<string> {
  return command.multiFlags.get(name) ?? [];
}

export function helpText(): string {
  return [
    "Usage: crossengin <command> [options]",
    "",
    "Commands:",
    "  init <output>           Scaffold a new manifest file",
    "  validate <path>         Validate a manifest against the kernel schema",
    "  diff <old> <new>        Compare two manifests",
    "  patch <base> <patch>    Apply a manifest patch (writes new manifest)",
    "  hash <path>             Print the deterministic manifest hash",
    "  apply [--dry-run] [--pack <slug>]",
    "                          Apply the meta-schema + optional vertical pack DDL",
    "  chat                    Interactive AI Architect session (Claude-backed)",
    "  sessions list           List persisted chat sessions (requires PG env)",
    "  sessions show <id>      Render one session's full transcript",
    "  sessions replay <id>    Replay one session as chat-style output",
    "  gateway start           Boot the API gateway runtime (defaults to PG mode)",
    "  gateway routes list     List PG-registered routes (requires PG env)",
    "  gateway routes register <route.json>",
    "                          Upsert a route from a JSON file (requires PG env)",
    "  gateway routes unregister <rt_id>",
    "                          Delete a route by id (requires PG env)",
    "  gateway routes register-pack <slug> [--api-version v1] [--dry-run]",
    "                          Generate + upsert CRUD + transition routes from a registered pack",
    "  gateway routes unregister-pack <slug> [--api-version v1] [--dry-run] [--by-source-pack]",
    "                          Delete every route whose id matches the regen for a pack",
    "                          (default), or DELETE WHERE source_pack = <slug> (--by-source-pack)",
    "  gateway routes sync-pack <slug> [--api-version v1] [--dry-run] [--created-by <uuid>] [--prune-obsolete]",
    "                          Upsert generated routes; classify stored as obsolete (this pack)",
    "                          vs external (other pack / unknown); optionally prune obsolete",
    "  gateway prune-idempotency [--dry-run] [--operation-id <id>] [--method <POST|PUT|PATCH|DELETE>] [--limit <n>]",
    "                          DELETE expired rows from meta.gateway_idempotency_records",
    "                          (WHERE expires_at < now()). The table has its own TTL via",
    "                          the expires_at column; no policy table required. With --dry-run,",
    "                          report the would-delete count without DELETEing. Optional",
    "                          --operation-id / --method scope the sweep; --limit caps the",
    "                          row count (batch-delete pattern for lock-contention safety).",
    "                          (requires PG env)",
    "  gateway housekeeping [--watch] [--watch-interval <seconds>]",
    "                       [--watch-keep-going] [--threshold-alert '<clause>[ AND <clause>...]' ...]",
    "                       [--tenant <uuid|slug> | --all-tenants]",
    "                          Unified read-only dashboard across the three gateway",
    "                          housekeeping tables (gateway_pipeline_executions,",
    "                          gateway_idempotency_records, rate_limit_decisions). Reports",
    "                          per-table total row count, oldest row timestamp, would-prune",
    "                          count, and (for retention-governed tables) the configured",
    "                          retention days + last_pruned_at. No DELETEs are issued.",
    "                          With --watch, re-renders every --watch-interval seconds",
    "                          (default 5, range [1, 3600]) for incident-room monitoring;",
    "                          human format clears the screen each tick, json streams",
    "                          NDJSON-of-envelopes. --watch requires --format human|json.",
    "                          Under --watch, Ctrl-C (SIGINT) AND graceful shutdown signals",
    "                          from container managers (SIGTERM from Kubernetes / systemd)",
    "                          exit cleanly via a shared shutdown-to-AbortController bridge",
    "                          (PG connection closes via the action's finally block).",
    "                          With --watch-keep-going, transient PG errors are caught +",
    "                          rendered (loop continues) and --threshold-alert trips are",
    "                          tracked but don't exit early; final exit is 3 if any tick",
    "                          ever tripped, else 0. Requires --watch.",
    "                          With --threshold-alert <clause>[ AND <clause>...] (repeatable),",
    "                          exits 3 when any alert trips on any table. Numeric fields:",
    "                          totalRowCount, wouldPruneCount, retentionDays. Timestamp",
    "                          fields: oldestAt, lastPrunedAt (use duration values like",
    "                          24h / 7d / 365d / 30m / 1y or ISO 8601). Ops: > >= < <= =.",
    "                          Compound expressions: 'A AND B' trips when BOTH clauses match;",
    "                          'A OR B' trips when EITHER matches (equivalent to two separate",
    "                          flags). Mixing AND + OR in one flag exits 2; use multiple flags",
    "                          for OR composition.",
    "                          With --tenant <uuid|slug>, each retention-governed table report",
    "                          adds a per-tenant override section (or '(no override —",
    "                          inherits platform default)'); idempotency table marks",
    "                          '(not applicable — expires_at-managed)'. Aggregates",
    "                          (totalRowCount, oldestAt, wouldPruneCount) stay cross-tenant",
    "                          for mental-model continuity; zero new substrate queries.",
    "                          With --all-tenants (mutually exclusive with --tenant), each",
    "                          retention-governed table report adds a `matrix` block listing",
    "                          every per-tenant override sorted by tenantId; idempotency",
    "                          table marks '(not applicable — expires_at-managed)'.",
    "                          Aggregates stay cross-tenant (same Option B drill-down as",
    "                          --tenant).",
    "                          --tenant accepts a UUID OR a slug from meta.tenants. UUIDs",
    "                          short-circuit; slugs resolve via one extra SELECT before the",
    "                          dashboard runs. Unknown slug exits 2 cleanly.",
    "                          (requires PG env)",
    "  retention expiring [--within-days N] [--include-expired]",
    "                          List per-tenant retention opt-outs whose opt_out_until falls",
    "                          within the configured window (default 30d). With --include-expired,",
    "                          also include already-expired opt-outs. (requires PG env)",
    "  retention effective <tenant-id> <table-name>",
    "                          Resolve the effective retention policy for a (tenant, table)",
    "                          pair: tenant override / tenant opt-out / platform default / none.",
    "                          (requires PG env)",
    "  retention effective-batch --pairs-file <path>",
    "                          Bulk-resolve effective retention for many (tenant, table)",
    "                          pairs read from a JSON file. File format: array of",
    "                          {tenantId, tableName} objects. Runs 2 PG queries total via",
    "                          effectiveRetentionBatch regardless of pair count. Preserves",
    "                          input order in output. (requires PG env)",
    "  retention opt-out <tenant-id> <table-name> [--until DATE] [--reason TEXT] [--retention-days N]",
    "                          Set opt_out=true on the (tenant, table) policy. Preserves",
    "                          existing retention_days; default 365 for new rows. --until and",
    "                          --reason both optional; not-provided means NULL. (requires PG env)",
    "  retention opt-in <tenant-id> <table-name>",
    "                          Clear opt_out (set false) and opt_out_until (NULL) for the",
    "                          (tenant, table) policy. Preserves opt_out_reason as audit",
    "                          history (per ADR-0161). Idempotent. (requires PG env)",
    "  retention set <tenant-id> <table-name> --days N [--enabled true|false]",
    "                          Set a non-opt-out per-tenant retention override. Clears any",
    "                          existing opt_out + opt_out_until on the row; preserves",
    "                          opt_out_reason as audit history (per ADR-0161). Default",
    "                          --enabled=true. (requires PG env)",
    "  retention delete <tenant-id> <table-name>",
    "                          Remove the per-tenant policy row entirely. Tenant inherits",
    "                          platform default. Idempotent (no-op when no matching row).",
    "                          (requires PG env)",
    "  retention history [--tenant <uuid>] [--table <name>] [--kind <event-kind> ...]",
    "                    [--kind-not <event-kind> ...]",
    "                    [--actor-id <uuid> ...] [--actor-id-not <uuid> ...]",
    "                    [--system-only | --no-system]",
    "                    [--since DATE] [--until DATE] [--limit N]",
    "                    [--after-id <uuid>] [--before-id <uuid>]",
    "                    [--range <after-id>..<before-id>] [--with-actor-names]",
    "                    [--explain]",
    "                          Query the append-only opt-out/policy mutation audit log.",
    "                          Filter by tenant / table / event kind / actor / time range.",
    "                          Default --limit=100. Sorted by occurred_at DESC, id DESC.",
    "                          With --after-id, paginate forward past the cursor row (older",
    "                          entries). With --before-id, paginate backward toward newer",
    "                          entries. --after-id and --before-id are mutually exclusive.",
    "                          With --range <after-id>..<before-id>, pass both cursors as",
    "                          a single flag for window-bounded pagination (events older",
    "                          than after-id AND newer than before-id). --range is",
    "                          mutually exclusive with bare --after-id / --before-id.",
    "                          Output gives nextAfterId + nextBeforeId for bidirectional",
    "                          navigation when the page is full. --kind is repeatable and",
    "                          filters the log to entries with any of the listed event_kinds",
    "                          (OR-semantic IN). --kind-not is repeatable and EXCLUDES",
    "                          entries with any of the listed event_kinds (OR-semantic NOT IN;",
    "                          mirror of --kind). --actor-id is repeatable",
    "                          and scopes the log to the listed actors' mutations (OR-",
    "                          semantic IN). --actor-id-not is repeatable and excludes",
    "                          events authored by any of the listed actors (OR-semantic",
    "                          NOT IN; system events with null actor_id are included).",
    "                          --system-only returns ONLY system-authored events",
    "                          (actor_id IS NULL); --no-system EXCLUDES system events",
    "                          (actor_id IS NOT NULL). --system-only and --no-system are",
    "                          mutually exclusive. --with-actor-names LEFT JOINs meta.users",
    "                          to surface actor display_name + email alongside raw UUIDs.",
    "                          (requires PG env)",
    "  retention summary [--group-by kind|tenant|actor|table|day|hour|week|month]",
    "                    [--then-by <dimension>]",
    "                    [--tenant <uuid>] [--table <name>] [--kind <event-kind> ...]",
    "                    [--kind-not <event-kind> ...] [--actor-id <uuid> ...]",
    "                    [--actor-id-not <uuid> ...] [--system-only | --no-system]",
    "                    [--since DATE] [--until DATE] [--fill-gaps]",
    "                    [--timezone <iana-tz>] [--top N] [--min-count N]",
    "                    [--top-per-group N] [--bottom-per-group N] [--explain]",
    "                          Aggregate opt-out/policy mutation history counts grouped by",
    "                          one dimension (--group-by; default kind). Returns buckets",
    "                          {key, count} plus a total. Categorical dimensions (kind /",
    "                          tenant / actor / table) sort by count DESC then key ASC;",
    "                          temporal dimensions (day / hour / week / month) sort",
    "                          chronologically (key ASC) via date_trunc(occurred_at) in UTC",
    "                          for histogram-style activity reports. actor null renders",
    "                          <system>. With --then-by <dimension> (must differ from",
    "                          --group-by), produce a cross-tab grid: composite buckets",
    "                          {key, subKey, count} ordered (primary ASC, secondary ASC),",
    "                          e.g. --group-by day --then-by kind for daily per-kind volume.",
    "                          With --fill-gaps (temporal --group-by + --since + --until",
    "                          required; incompatible with --then-by), emit zero-count",
    "                          buckets for empty time periods so histograms have no gaps.",
    "                          With --timezone <iana-tz> (temporal grouping only; default",
    "                          UTC), bucket day/hour/week/month boundaries in that timezone",
    "                          (e.g. America/New_York midnight). With --top N, return only",
    "                          the N highest-count buckets (forces count-DESC ordering).",
    "                          With --min-count N, omit buckets with fewer than N events",
    "                          (HAVING threshold). With --then-by, --top-per-group N keeps",
    "                          only the top N sub-keys within each primary group (ROW_NUMBER",
    "                          window — e.g. --group-by day --then-by actor --top-per-group 3",
    "                          for top 3 actors per day); --bottom-per-group N keeps the",
    "                          bottom (lowest-count) N sub-keys instead. Both require",
    "                          --then-by and are mutually exclusive with --top and each other.",
    "                          --top / --min-count / --top-per-group / --bottom-per-group are",
    "                          incompatible with",
    "                          --fill-gaps (opposite intents). Accepts the same filters",
    "                          as 'history' (--tenant /",
    "                          --table / --kind / --kind-not / --actor-id / --actor-id-not /",
    "                          --system-only / --no-system / --since / --until). Supports",
    "                          --format json|csv|tsv|ndjson + --explain. (requires PG env)",
    "  retention restore <history-id> [--dry-run] [--actor <uuid>]",
    "                          Restore a per-tenant policy to the state captured in",
    "                          tenant_retention_opt_out_history. prev_state=null restores",
    "                          via DELETE; populated prev_state restores via setTenantOptOut",
    "                          or setTenantRetention depending on prev_state.opt_out. Writes",
    "                          a new history row with attributes.restored_from = history-id.",
    "                          With --dry-run, show prev_state + planned mutation method",
    "                          without applying. (requires PG env)",
    "                          All 5 mutation/restore actions accept --attributes '<json>'",
    "                          where <json> is a JSON object merged into the history row's",
    "                          attributes JSONB column. Restore merges {restored_from:",
    "                          historyId} with operator-supplied attributes. Invalid JSON or",
    "                          non-object value returns exit 2.",
    "  retention diff-history <history-id-a> <history-id-b> [--kind <event-kind> ...]",
    "                          [--kind-a <event-kind> ...] [--kind-b <event-kind> ...]",
    "                          [--kind-not <event-kind> ...]",
    "                          [--kind-not-a <event-kind> ...]",
    "                          [--kind-not-b <event-kind> ...]",
    "                          [--actor-id <uuid> ...] [--actor-id-a <uuid> ...] [--actor-id-b <uuid> ...]",
    "                          [--actor-id-not <uuid> ...] [--actor-id-not-a <uuid> ...]",
    "                          [--actor-id-not-b <uuid> ...] [--system-only | --no-system]",
    "                          [--system-only-a | --no-system-a]",
    "                          [--system-only-b | --no-system-b]",
    "                          [--with-actor-names] [--explain]",
    "                          Compare the policy state captured in two history events",
    "                          (next_state vs next_state). Both events must be on the same",
    "                          (tenant, table). Renders field-by-field diff. --kind is",
    "                          repeatable — assert both events have any of the listed",
    "                          event_kinds (opt_out_set | opt_out_cleared | retention_set |",
    "                          policy_deleted); mismatch by either side on any kind not in",
    "                          the listed set exits 1 with a clear error naming the",
    "                          offending side(s).",
    "                          --kind-a / --kind-b are repeatable per-side expectations —",
    "                          assert side A / side B has any of the listed event_kinds",
    "                          (OR-semantic tuple expectation); per-side fires independently",
    "                          of --kind global and after it in the check order. --kind-not is",
    "                          repeatable — assert NEITHER event has any of the listed",
    "                          event_kinds; match by either side on any listed kind exits",
    "                          1 (anti-kind verification, mirror of --kind). --kind-not-a /",
    "                          --kind-not-b are repeatable per-side exclusions — assert",
    "                          side A / side B does NOT have any of the listed kinds.",
    "                          --actor-id is repeatable — assert both events were authored",
    "                          by any of the listed actors (OR-semantic tuple expectation);",
    "                          mismatch by either side on any actor not in the listed set",
    "                          exits 1 (null actor_id renders as <system>).",
    "                          --actor-id-a / --actor-id-b are repeatable per-side",
    "                          expectations — assert side A / side B has any of the listed",
    "                          actors (OR-semantic tuple); per-side fires independently.",
    "                          --actor-id-not is",
    "                          repeatable — assert NEITHER event was authored by any of",
    "                          the listed actors (OR-semantic exclusion); match by either",
    "                          side on any listed actor exits 1 (anti-actor verification,",
    "                          mirror of --actor-id). --actor-id-not-a /",
    "                          --actor-id-not-b are repeatable per-side exclusions —",
    "                          assert side A / side B is NOT any of the listed actors.",
    "                          With --system-only, assert BOTH events are system-authored",
    "                          (actor_id IS NULL); with --no-system, assert NEITHER event",
    "                          is system-authored (actor_id IS NOT NULL). --system-only",
    "                          and --no-system are mutually exclusive; mismatch exits 1.",
    "                          --system-only-a / --no-system-a / --system-only-b /",
    "                          --no-system-b are per-side actor-presence assertions —",
    "                          assert side A / side B is or is not system-authored.",
    "                          --system-only-X and --no-system-X are mutually exclusive",
    "                          per side; A's and B's flags don't interact (operators can",
    '                          set --system-only-a + --no-system-b for asymmetric "A is',
    '                          system, B is human" assertion). Per-side fires after global.',
    "                          With --with-actor-names, LEFT JOIN meta.users so the header",
    "                          renders 'by display_name (uuid)' per event (falls back to",
    "                          email then raw UUID; null actor_id renders as <system>).",
    "                          (requires PG env)",
    "  retention diff-timeline <tenant-a> <tenant-b> <table-name>",
    "                          [--add-tenant <tenant-c> ...] [--since DATE]",
    "                          [--until DATE] [--limit N] [--with-actor-names]",
    "                          [--actor-id <uuid>] [--actor-id-not <uuid>]",
    "                          [--system-only | --no-system]",
    "                          [--kind <event-kind> ...] [--kind-not <event-kind> ...]",
    "                          [--explain] [--after-id <uuid>]",
    "                          [--before-id <uuid>]",
    "                          [--range <after-id>..<before-id>]",
    "                          Show how two (or more) tenants' retention policies evolved over",
    "                          time on one table. Merges history events into a single",
    "                          chronological timeline (ASC). Each event tagged with [A]/[B]/...",
    "                          indicating which tenant changed. With --add-tenant <uuid>",
    "                          (repeatable): N-way merge across 3+ tenants. With",
    "                          --with-actor-names: LEFT JOIN meta.users + render",
    "                          'display_name (uuid)' alongside each event. --actor-id is",
    "                          repeatable — single value scopes to one actor's events,",
    "                          multiple values build an OR-semantic IN filter ('Alice OR",
    "                          Bob's mutations'). --actor-id-not is also repeatable —",
    "                          excludes events authored by listed actor(s) (system events",
    "                          with null actor_id are included). --system-only returns ONLY",
    "                          system-authored events (actor_id IS NULL); --no-system",
    "                          EXCLUDES system events (actor_id IS NOT NULL). --system-only",
    "                          and --no-system are mutually exclusive. --kind is repeatable",
    "                          (same OR semantic) across opt_out_set|opt_out_cleared|",
    "                          retention_set|policy_deleted — invalid value exits 2.",
    "                          --kind-not is repeatable and EXCLUDES entries with any of the",
    "                          listed event_kinds (OR-semantic NOT IN; mirror of --kind). With",
    "                          --after-id: cursor forward in time (newer entries since",
    "                          diff-timeline is ASC). With --before-id: cursor backward toward",
    "                          older entries. --after-id and --before-id are mutually",
    "                          exclusive. With --range <after-id>..<before-id>, pass both",
    "                          cursors as a single flag for window-bounded pagination",
    "                          (mutually exclusive with bare --after-id / --before-id).",
    "                          Output gives nextAfterId + nextBeforeId when page is full.",
    "                          (requires PG env)",
    "  retention diff-timeline <tenant> <table-a> <table-b> --cross-table",
    "                          [--add-table <table-c> ...] [--since DATE] [--until DATE]",
    "                          [--limit N] [--with-actor-names] [--actor-id <uuid>]",
    "                          [--actor-id-not <uuid>]",
    "                          [--system-only | --no-system] [--kind <event-kind> ...]",
    "                          [--kind-not <event-kind> ...]",
    "                          [--after-id <uuid>] [--before-id <uuid>]",
    "                          [--range <after-id>..<before-id>] [--explain]",
    "                          Show how one tenant's retention policies evolved over time",
    "                          across 2+ tables. Merges history events from multiple tables",
    "                          into a single chronological timeline tagged with [A]/[B]/...",
    "                          indicating which table changed. --add-table requires",
    "                          --cross-table; mutually exclusive with --add-tenant.",
    "                          --actor-id + --actor-id-not + --kind + --kind-not all",
    "                          repeatable for OR-semantic multi-value filters. --system-only / --no-system",
    "                          filter to / exclude system-authored events (mutually",
    "                          exclusive). --after-id cursors forward, --before-id cursors",
    "                          backward (mutually exclusive). With --range",
    "                          <after-id>..<before-id>, single-flag window cursor.",
    "                          Output gives nextAfterId + nextBeforeId when page is full.",
    "                          (requires PG env)",
    "  retention diff <tenant-a> <tenant-b> <table-name>",
    "                          Compare effective retention policies between two tenants on",
    "                          the same table. Reuses effectiveRetentionBatch internally (2",
    "                          queries total). Renders resolution summary per tenant + field",
    "                          diff. (requires PG env)",
    "  retention diff <tenant> <table-name> --vs-platform",
    "                          Compare a tenant's effective retention against the platform",
    "                          default for the same table. 2 parallel queries — tenant +",
    "                          platform. Useful for one-command 'how does this tenant differ",
    "                          from the default?' checks vs running two retention effective",
    "                          calls and mental-diffing. (requires PG env)",
    "  retention diff <tenant> <table-a> <table-b> --cross-table",
    "                          Compare one tenant's effective retention across two different",
    "                          tables. Reuses effectiveRetentionBatch internally (2 queries",
    "                          total). Useful for 'is this tenant's retention consistent",
    "                          across all trace tables?' audits. Mutually exclusive with",
    "                          --vs-platform. (requires PG env)",
    "  retention diff <a> <b> <table> --add-tenant <c> [--add-tenant <d> ...]",
    "                          N-way comparison across 3+ tenants on the same table.",
    "                          Renders per-field variation analysis (which tenants have",
    "                          which value). Repeats --add-tenant for each extra tenant.",
    "                          Mutually exclusive with --vs-platform and --cross-table.",
    "                          (requires PG env)",
    "  retention diff <tenant> <table-a> <table-b> --cross-table --add-table <table-c>",
    "                                                            [--add-table <table-d> ...]",
    "                          N-way comparison across 3+ tables for one tenant. Renders",
    "                          per-field variation analysis (which tables have which value).",
    "                          Requires --cross-table. Mutually exclusive with --vs-platform",
    "                          and --add-tenant. (requires PG env)",
    "                          All four diff variants accept --exit-on-divergence which",
    "                          returns exit 3 (instead of 0) when fieldDiffs is non-empty —",
    "                          for CI gates that fail the build when retention drifts.",
    "                          Pair with --threshold N (default 1) to require N+ field",
    "                          differences before exit 3 fires. --threshold requires",
    "                          --exit-on-divergence; invalid values exit 2.",
    "  retention prune [--dry-run]",
    "                          Run retention pruning ad-hoc (normally invoked via scheduled",
    "                          job). With --dry-run, count rows that would be deleted",
    "                          without actually deleting. Renders per-table + per-tenant",
    "                          results with a summary line. (requires PG env)",
    "  retention list-policies [--tenant <uuid>] [--table <name>]",
    "                          List all retention policies (platform defaults + per-tenant",
    "                          overrides). Optional --tenant scopes the per-tenant section;",
    "                          optional --table scopes both sections. (requires PG env)",
    "  retention housekeeping [--watch] [--watch-interval <seconds>]",
    "                         [--watch-keep-going] [--threshold-alert '<clause>[ AND <clause>...]' ...]",
    "                         [--tenant <uuid|slug> | --all-tenants]",
    "                          Unified read-only dashboard across ALL 6 retention-substrate-",
    "                          governed tables (workflow_traces, llm_call_traces,",
    "                          llm_latency_samples, tenant_retention_opt_out_history,",
    "                          gateway_pipeline_executions, rate_limit_decisions). Reports",
    "                          per-table total rows, oldest row, would-prune count, retention",
    "                          policy + last-pruned, and per-tenant override count. Issues NO",
    "                          DELETEs. Complements gateway housekeeping (which is the",
    "                          operator-domain view scoped to gateway tables + their",
    "                          idempotency-store sibling). With --watch, re-renders every",
    "                          --watch-interval seconds (default 5, range [1, 3600]) for",
    "                          incident-room monitoring; --watch requires --format human|json.",
    "                          Under --watch, Ctrl-C (SIGINT) AND graceful shutdown signals",
    "                          from container managers (SIGTERM from Kubernetes / systemd)",
    "                          exit cleanly via a shared shutdown-to-AbortController bridge",
    "                          (PG connection closes via the action's finally block).",
    "                          With --tenant <uuid|slug>,",
    "                          adds a per-table tenantPolicy field showing the named",
    "                          tenant's override (or 'no override' when none); aggregate",
    "                          fields stay cross-tenant for the operator's overall view.",
    "                          With --all-tenants (mutually exclusive with --tenant), adds",
    "                          a per-table matrix block listing every per-tenant override",
    "                          sorted by tenantId; same aggregate semantic.",
    "                          With --watch-keep-going (requires --watch), transient PG",
    "                          errors are caught + rendered and threshold-alert trips are",
    "                          tracked without halting; final exit is 3 if any tick tripped.",
    "                          With --threshold-alert <clause>[ AND <clause>...] (repeatable), exits",
    "                          3 when any alert trips on any table. Numeric fields:",
    "                          totalRowCount, wouldPruneCount, retentionDays,",
    "                          perTenantPolicyCount. Timestamp fields: oldestAt, lastPrunedAt",
    "                          (use duration values like 24h / 7d / 30m / 1y or ISO 8601).",
    "                          Compound expressions: 'A AND B' trips when BOTH clauses match;",
    "                          'A OR B' trips when EITHER matches (equivalent to two separate",
    "                          flags). Mixing AND + OR in one flag exits 2.",
    "                          --tenant accepts a UUID OR a slug from meta.tenants. UUIDs",
    "                          short-circuit; slugs resolve via one extra SELECT before the",
    "                          dashboard runs. Unknown slug exits 2 cleanly.",
    "                          (requires PG env)",
    "  tenant housekeeping [--tenant <uuid|slug> | --all-tenants]",
    "                      [--diff <other-uuid|slug> [--add-tenant <other>]...",
    "                         [--exit-on-divergence [--threshold N]]]",
    "                      [--threshold-alert '<clause>[ AND <clause>...]' ...]",
    "                      [--watch [--watch-interval <secs>] [--watch-keep-going]]",
    "                          Cross-dashboard combined view: runs BOTH gateway housekeeping",
    "                          AND retention housekeeping under the same --tenant filter (or",
    "                          --all-tenants) and concatenates output in one envelope.",
    "                          Single PG connection; single slug resolution; threshold-alerts",
    "                          evaluate across the union of all tables from both dashboards.",
    "                          Designed for compliance audits spanning both operator-domain",
    "                          (gateway) and substrate-centric (retention) views in one command.",
    "                          With --watch, loops in-process at --watch-interval seconds",
    "                          (default 5, range 1..3600), each tick gathering BOTH dashboards",
    "                          AND evaluating alerts ATOMICALLY before a single render — no",
    "                          interleaved-render layout garbling. Threshold-alert trips exit",
    "                          the loop with exit 3; --watch-keep-going records trips as",
    "                          'ever halted' but continues running (catches gather errors too)",
    "                          for incident-monitoring resilience. SIGINT + SIGTERM both",
    "                          drain cleanly via the shared shutdown bridge.",
    "                          With --diff <other-uuid|slug>, switches to pair-wise comparison",
    "                          mode: gathers BOTH dashboards for BOTH tenants (4 reports total),",
    "                          computes per-tenantPolicy field divergences across gateway +",
    "                          retention tables, and emits tenant.housekeeping.diff envelope.",
    "                          Requires --tenant (LHS); --diff supplies RHS. Mutually exclusive",
    "                          with --all-tenants, --watch, --threshold-alert. Self-diff guard.",
    "                          With --add-tenant <other> (repeatable, requires --diff), extends",
    "                          to N-way: each --add-tenant adds another RHS compared against",
    "                          the anchor. When N>1, envelope becomes tenant.housekeeping.diff.",
    "                          multi with anchor + comparisons[] array; exit code = MAX-",
    "                          divergence across comparisons (any comparison's fieldDiffs.length",
    "                          ≥ threshold trips exit 3). Duplicate-target guards reject same",
    "                          RHS in multiple slots. Useful for cohort uniformity sampling.",
    "                          (requires PG env)",
    "  tenant policies <slug|uuid> [--effective] [--explain]",
    "                          [--diff <other-slug|uuid> [--add-tenant <other>]... |",
    "                           --vs-tier <tier-id> [--vs-tier <tier-id>]...]",
    "                          [--exit-on-divergence [--threshold N]]",
    "                          Per-tenant cross-substrate policy summary: aggregates retention",
    "                          overrides + cost-ceiling override + tier membership for one",
    "                          tenant under one envelope. Resolves slug→UUID via the same path",
    "                          as `tenants resolve` (inherits 'did you mean' suggestions on slug",
    "                          typos). Output: human key:value sections with placeholders for",
    "                          empty axes, or JSON envelope with all three axes preserved.",
    "                          With --effective, ALSO renders a fourth section showing the",
    "                          precedence-resolved ceiling (override→tier→none walk; mirrors",
    "                          PostgresCostCeilingResolver.resolveDetailed source attribution).",
    "                          With --explain (implies --effective), adds a what-if block",
    "                          showing what the precedence walk would yield if the override or",
    "                          tier was stripped — operators auditing whether their override is",
    "                          actually doing anything different from the tier compare the",
    "                          `effective` block to `explain.withoutOverride`. Mutually",
    "                          exclusive with --diff in v1.",
    "                          With --diff <other>, compares two tenants' policy shapes side-",
    "                          by-side across all three axes; emits a fieldDiffs list grouped",
    "                          by axis (retention / costCeiling / tier). Composes with",
    "                          --effective (both sides get the effective field). Pair with",
    "                          --exit-on-divergence (exit 3 when fieldDiffs.length ≥ threshold,",
    "                          default 1) for CI integration.",
    "                          With --vs-tier <tier-id>, compares the tenant against a SYNTHETIC",
    "                          right-hand-side built from the same tenant with the same retention",
    "                          + same cost-ceiling override but the tier replaced by <tier-id>",
    "                          (looked up from meta.llm_cost_tiers). Answers 'what would change",
    "                          if I moved this tenant to <tier-id>?' before committing a",
    "                          membership change. Pair with --effective so both sides carry",
    "                          their effective-ceiling field — operators read whether the",
    "                          effective ceiling actually changes (it doesn't when override",
    "                          shadows the tier; canonical 'your override is doing all the work'",
    "                          finding). Mutually exclusive with --diff and --explain.",
    "                          With --add-tenant <other> (repeatable, requires --diff), extends",
    "                          --diff into N-way comparison: each --add-tenant adds another RHS",
    "                          compared against the anchor. Repeated --vs-tier flags do the same",
    "                          for tier comparisons. When N>1, the envelope changes to",
    "                          tenant.policies.diff.multi (json) with comparisons[] array, or",
    "                          adds a comparison_index column (csv/tsv). Exit code is MAX-",
    "                          divergence across comparisons: any comparison's fieldDiffs.length",
    "                          ≥ threshold trips exit 3. Useful for cohort uniformity sampling",
    "                          + multi-tier preview matrix. Duplicate targets rejected.",
    "                          With --format csv|tsv [--csv-separator <ch>], emits a flat row-per-",
    "                          axis schema: retention rows (one per table), cost_ceiling row,",
    "                          tier row, effective row (under --effective), explain.* rows (under",
    "                          --explain). Wide header with axis-irrelevant fields rendered as",
    "                          empty cells; NUMERIC(18,8) string preservation for ceiling fields",
    "                          so spreadsheet round-trips don't lose precision. Under --diff,",
    "                          emits one row per fieldDiff with tenant_a / tenant_b columns;",
    "                          empty fieldDiffs still emit the header row (valid CSV for",
    "                          spreadsheet workflows even when policies match).",
    "                          (requires PG env)",
    "                          Rate-limit per-tenant overrides not included in v1 (substrate has",
    "                          no per-tenant override table today; tenant variation goes through",
    "                          tier membership).",
    "  tenants list [--status <s>] [--table-filter <name>] [--has-overrides]",
    "               [--format csv|tsv [--csv-separator <c>]]",
    "                          Enumerate tenants from meta.tenants. Optional filters: --status",
    "                          (active|suspended|archived|deleted) matches the schema CHECK;",
    "                          --table-filter <name> narrows to tenants with a per-tenant policy",
    "                          on that table; --has-overrides narrows to tenants with at least",
    "                          one per-tenant policy on any table. Sorted by slug. With --format",
    "                          csv|tsv: 5-column bulk export (id, slug, name, status, tier) ready",
    "                          for spreadsheet/pandas workflows; empty result still emits header.",
    "                          --csv-separator <c> overrides comma (rejects '\"' and newlines).",
    "                          (requires PG env)",
    "  tenants resolve <slug|uuid>",
    "                          One-shot UUID lookup helper for shell scripting. UUIDs short-",
    "                          circuit; slugs resolve via meta.tenants. Output (human format):",
    "                          just the UUID + newline so `crossengin tenants resolve acme-prod",
    "                          | xargs -I {} crossengin gateway housekeeping --tenant {}` works.",
    "                          Unknown slug exits 2. (requires PG env)",
    "  tenants get <slug|uuid>",
    "                          Fetch one tenant's full record (all 11 META_TENANTS columns:",
    "                          id, slug, name, status, tier, region, schema, residency,",
    "                          search_locale, created_at, updated_at). Resolves slug→UUID via",
    "                          the same path as `tenants resolve` (inherits 'did you mean'",
    "                          suggestions on slug typos). Unknown UUID exits 2 with a distinct",
    "                          'no tenant with id' error. (requires PG env)",
    "  workflow validate <def.json> [--strict]",
    "                          Run the workflow definition pre-publish validator (ADR-0256).",
    "                          Schema-parses the JSON, then runs validateDefinition. Exit 0",
    "                          on ok, 2 on schema/parse errors, 3 on validation errors. With",
    "                          --strict, also fail on warnings (exit 3).",
    "  version                 Print the CLI version + workspace info",
    "  help                    Show this help text",
    "",
    "Flags:",
    "  --format human|json|csv|tsv|ndjson|yaml",
    "                          Output format (default: human). csv/tsv/ndjson are",
    "                          supported on list-style retention actions (history +",
    "                          diff-timeline); diff-history csv/tsv emits field-diff",
    "                          rows. ndjson emits one entry per line (no envelope).",
    "                          yaml emits the same structured envelope as json, in YAML.",
    "  --csv-separator CHAR    Custom CSV separator (default: ','). Only applies to",
    "                          --format=csv. Cannot be '\"' or newline.",
    "  --force                 With init / patch, overwrite an existing file",
    "  --output <path>         With patch, write the result to a different path",
    "  --dry-run               With apply, emit SQL without executing",
    "  --explain               With retention history / diff-history / diff-timeline /",
    "                          summary, print the query plan (filters + pagination + raw",
    "                          SQL + bound params) without executing. Debug aid.",
    "  --explain-analyze       Like --explain, but EXECUTE the query via EXPLAIN (ANALYZE,",
    "                          FORMAT JSON) and return PG's real execution plan with timing",
    "                          + row counts. Read-only (SELECT output discarded). Mutually",
    "                          exclusive with --explain.",
    "  --confirm               Required when PGDATABASE looks like production",
    "  --pack <slug>           With apply, also emit DDL for a vertical pack",
    "                          (e.g. 'operate-erp/core')",
    "  --pack-schema <name>    With --pack, the target schema (default: 'public')",
    "  --prompt <text>         With chat, run a one-shot turn and exit",
    "  --model <id>            With chat, pick a Claude model (default: claude-sonnet-4-6)",
    "  --max-tokens <n>        With chat, cap response tokens (default: 4096)",
    "  --system <text>         With chat, override the system prompt",
    "  --system-file <path>    With chat, load the system prompt from a file",
    "  --tenant-id <uuid>      With chat, set the tenant id (default: nil-uuid)",
    "  --session-id <id>       With chat, set the session id (default: cli-<ts>)",
    "  --no-tools              With chat, disable manifest tools (text-only mode)",
    "  --allow-file-read       With chat, expose a read_file tool (json/yaml/txt/md)",
    "  --allow-file-write      With chat, expose propose_manifest_edit (human approval)",
    "  --auto-approve-writes   With chat, skip the y/N prompt for write tools",
    "  --max-tool-iterations N With chat, cap tool-dispatch loops per turn (default: 5)",
    "  --persist               With chat, log session/messages/tools/proposals to Postgres",
    "  --cost-ceiling-usd N    With chat, refuse calls whose estimated cost exceeds N USD",
    "  --port <n>              With gateway start, listen on port (default: 8080)",
    "  --host <addr>           With gateway start, bind to address (default: 127.0.0.1)",
    "  --in-memory             With gateway start, use in-memory stores (no PG required)",
    "  --jwks-file <path>      With gateway start, enable Bearer-JWT auth from a JWKS JSON file",
    "  --jwks-url <url>        With gateway start, fetch the JWKS from an HTTPS endpoint",
    "                          (mutually exclusive with --jwks-file)",
    "  --jwks-refresh-seconds N  Periodic JWKS reload interval (default 300 for --jwks-url, 0 for file)",
    "  --jwt-issuer <iss>      With --jwks-file/--jwks-url, expected JWT issuer (required)",
    "  --jwt-audience <aud>    With --jwks-file/--jwks-url, expected JWT audience (required)",
    "  --clock-skew-seconds N  With --jwks-file/--jwks-url, exp/nbf grace window (default 30, max 600)",
    "  --created-by <uuid>     With 'gateway routes register', the actor uuid stored on the route",
    "  --prune-obsolete        With 'gateway routes sync-pack', delete stored routes that were",
    "                          registered by this pack but are no longer in the current generation",
    "  --by-source-pack        With 'gateway routes unregister-pack', skip the manifest pipeline",
    "                          and DELETE WHERE source_pack = <slug>. Works without resolvePack/",
    "                          tryValidateManifest (useful when the pack manifest is broken)",
    "  --within-days N         With 'retention expiring', the window upper bound in days (default 30)",
    "  --include-expired       With 'retention expiring', also surface already-expired opt-outs",
    "  --until DATE            With 'retention opt-out', ISO 8601 timestamp when the opt-out expires",
    "                          (omit for indefinite)",
    "  --reason TEXT           With 'retention opt-out', audit context (length 1..256, omit for null)",
    "  --retention-days N      With 'retention opt-out', placeholder retention_days for new rows",
    "                          (default 365; preserves existing on ON CONFLICT)",
    "  --tenant <uuid>         With 'retention list-policies', filter per-tenant section to one tenant",
    "  --table <name>          With 'retention list-policies', filter both sections to one table",
    "  --days N                With 'retention set', retention_days (integer >= 1; required)",
    "  --enabled true|false    With 'retention set', set enabled flag (default true)",
    "  --actor <uuid>          With opt-out / opt-in / set / delete, actor id recorded in",
    "                          tenant_retention_opt_out_history (optional; null when omitted)",
    "  --kind <event-kind>     With 'retention history', filter by event_kind",
    "                          (opt_out_set | opt_out_cleared | retention_set | policy_deleted).",
    "                          Repeatable for multi-value OR-semantic IN filter.",
    "  --since DATE            With 'retention history', lower bound on occurred_at (ISO 8601)",
    "  --until DATE            With 'retention history', upper bound on occurred_at (ISO 8601)",
    "  --limit N               With 'retention history', max entries to return (default 100)",
    "  --after-id <uuid>       With 'retention history', cursor for forward pagination",
    "                          (returns entries strictly older than the cursor row)",
    "",
    "Environment (for apply / chat --persist / gateway start / gateway routes / retention):",
    "  PGHOST, PGPORT, PGUSER, PGPASSWORD, PGDATABASE, PGSSLMODE, PGAPPNAME",
    "",
    "Environment (for chat):",
    "  ANTHROPIC_API_KEY       Anthropic API key. At least one chat provider is required.",
    "  OPENAI_API_KEY          OpenAI API key. With two+ providers set, the router fans out.",
    "  AWS_ACCESS_KEY_ID,      AWS credentials for Bedrock (chat + embeddings). Optionally",
    "  AWS_SECRET_ACCESS_KEY     AWS_SESSION_TOKEN (STS) + AWS_REGION (default: us-east-1).",
    "",
  ].join("\n");
}
